on:
  push:
    tags:
      - "v*"
name: Deploy Tagged Release
env:
  # the name of the repo
  HOME_REPO: david-waltermire-nist/metaschema
  HOME_BRANCH_RELEASE: main
  HOME_BRANCH_DEVELOPMENT: develop
  # paths
  REPO_PATH: git-content/metaschema-java
jobs:
  deploy-to-nexus:
    name: Build and Publish Java Artifacts
    runs-on: ubuntu-18.04
    steps:
      # use this for main repo builds
      - uses: actions/checkout@v2
        with:
          path: ${{ env.REPO_PATH }}
          submodules: recursive
      # -------------------------
      # Setup GPG
      - name: Install GPG Private Key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      # -------------------------
      # Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      # -------------------------
      # Maven Deploy
      - name: Deploy Maven Artifacts
        run: |
            mvn -s build/maven-release-settings.xml -Prelease deploy
            # mvn -s build/maven-release-settings.xml -Prelease nexus-staging:close -DstagingDescription="closing to release"
        working-directory: ${{ env.REPO_PATH }}
      - name: Gathering JAR files
        run: mkdir staging && cp target/*.jar staging
        working-directory: ${{ env.REPO_PATH }}
      - name: Saving staging artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
  deploy-website:
    name: Build and Publish Website
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.REPO_PATH }}
          submodules: recursive
      # -------------------------
      # Java JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      # -------------------------
      # Maven Deploy Website
      - name: Deploy Website
        run: |
            mvn -Preporting -Prelease package site site:stage
        working-directory: ${{ env.REPO_PATH }}
      - name: Run deploy script
        run: |
          touch target/staging/.nojekyll
          bash build/deploy.sh --push-only -v -m "Deploying website [ci skip]"
      - name: Gathering JAR files
        run: mkdir staging && cp target/*.jar staging
        working-directory: ${{ env.REPO_PATH }}
      - name: Saving staging artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
